name: Google Bigquery integration

# Controls when the action will run.
on:
  #push:
  #  branches: main
  #schedule:
  #  - cron: '0 2,9,14,20 * * *'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.15' # install the python version needed
          
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "config.json"
          json: ${{ secrets.CONFIG_JSON }}
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pandas google.cloud.bigquery pandas-gbq
                    
      - name: execute py script # run sj-gobierno.py to get the latest data
        run: python teste.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  
